### PR TITLE
Add support for Redis clusters.

### PR DESCRIPTION
**Pull request by wjharney**
From the [ioredis docs](https://github.com/luin/ioredis/blob/master/README.md#transaction-and-pipeline-in-cluster-mode):

>Almost all features that are supported by Redis are also supported by Redis.Cluster, e.g. custom commands, transaction and pipeline.

All of the features used here are supported by Redis.Cluster, so they should be accepted as well.

### CODE REVIEW

**Comment by natesilva** [comment]
We needed this, so we built [keyv-anyredis](https://github.com/natesilva/keyv-anyredis). It supports ioredis in cluster mode, and many other Redis clients.

**Comment by jbegleiter-sf** [comment]
@lukechilds is there a plan to continue to maintain/update these adaptors?

**Comment by jaredwray** [comment]
@wjharney can you let me know the best way to test this out in cluster mode? Also, we will need to add some tests around this. Thoughts?

**Review by jaredwray — COMMENTED** [review]
Can we get some tests around this?

**Pull request merged**
